pthread_create:pthread_create.c
	gcc $^  -o $@   -lpthread

pthread_join:pthread_join.c
	gcc $^  -o  $@  -lpthread

pthread_detach:pthread_detach.c
	gcc $^  -o  $@  -lpthread

pthread_exit:pthread_exit.c
	gcc $^  -o  $@  -lpthread
