fork:fork.c
	gcc fork.c -o fork

guer:guer.c
	gcc guer.c -o guer

jiangshi:jiangshi.c
	gcc jiangshi.c -o jiangshi

open:open.c
	gcc open.c -o open

execl:execl.c
	gcc execl.c -o execl

.PHONY:clean
clean:
	rm fork
